name: Continuous Integration (Lint and Test)
run-name: Continuous Integration triggered by a ${{ github.event_name }} on ${{ github.ref }} from ${{ github.actor }}
on:
  push:
    paths-ignore:
      - '*.md'
      - '*.rst'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.rst'

jobs:
  lint-type-check-and-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            python-version: '3.11'
            os: ubuntu-latest
            tox: py311
          - name: Windows
            python-version: '3.11'
            os: windows-latest
            tox: py311
          - name: Mac
            python-version: '3.11'
            os: macos-latest
            tox: py311
          - name: Static
            python-version: '3.11'
            os: ubuntu-latest
            tox: static

    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} to ${{ github.ref }}."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -U -e .[dev]
      - name: Cache mypy
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python }}|${{ hashFiles('pyproject.toml') }}
        if: matrix.tox == 'static'
      - run: tox run -e ${{ matrix.tox }}